fix: use mirromutth/mysql-action instead of icomponent/mysql-action (#576)
Error: Unable to resolve action icomponent/mysql-action, repository not found